name: FinPilot AI CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  app-build:
    name: Build Application
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: finpilot-ai-app

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build Application
        run: npm run build

  infra-check:
    name: Infra Validation
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: finpilot-ai-infra

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Check Infra Folder
        run: |
          echo "Infra directory present"
          ls -la

  gitops-check:
    name: GitOps Validation
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: finpilot-ai-gitops

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Check GitOps Folder
        run: |
          echo "GitOps directory present"
          ls -la